from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

from cppmega_mlx.data.domain_ingestion import (
    DOMAIN_INPUT_SIZE_LIMIT_BYTES,
    DiscoveredDomainFile,
    discover_project_domain_files,
    iter_domain_file_chunks,
    parse_domain_document,
)
from cppmega_mlx.data.domain_packet import wrap_with_domain_tokens
from cppmega_mlx.data.domain_schema import (
    DomainEdgeKind,
    DomainKind,
    ParseConfidence,
    delimiter_token_ids,
)


def _vtk_style_large_sql() -> str:
    statement = (
        'INSERT INTO "alias_name" VALUES('
        "'geodetic_datum','EPSG','6143',"
        "'Côte d''Ivoire; alias','EPSG'); "
    )
    repetitions = DOMAIN_INPUT_SIZE_LIMIT_BYTES // len(statement.encode("utf-8")) + 32
    text = "-- generated by scripts/build_db.py\n" + statement * repetitions + "\n"
    assert len(text.encode("utf-8")) > DOMAIN_INPUT_SIZE_LIMIT_BYTES
    return text


def _aseprite_style_large_configure() -> str:
    line = "printf '%s\\n' 'checking generated feature' > /dev/null\n"
    repetitions = DOMAIN_INPUT_SIZE_LIMIT_BYTES // len(line.encode("utf-8")) + 64
    text = "#!/bin/sh\n# Generated by GNU Autoconf.\n" + line * repetitions
    assert len(text.encode("utf-8")) > DOMAIN_INPUT_SIZE_LIMIT_BYTES
    return text


def test_large_sql_chunks_are_bounded_deterministic_and_lossless(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    from tools.clang_indexer import index_project

    sql = _vtk_style_large_sql()
    encoded = sql.encode("utf-8")
    sql_path = tmp_path / "ThirdParty/libproj/vtklibproj/data/sql/alias_name.sql"
    sql_path.parent.mkdir(parents=True)
    sql_path.write_bytes(encoded)

    original_read_text = Path.read_text

    def reject_whole_file_read(path: Path, *args, **kwargs):
        if path == sql_path:
            raise AssertionError("large SQL discovery must not call Path.read_text")
        return original_read_text(path, *args, **kwargs)

    monkeypatch.setattr(Path, "read_text", reject_whole_file_read)
    assert discover_project_domain_files(tmp_path) == [
        DiscoveredDomainFile(
            path=sql_path,
            domain=DomainKind.SQL,
            adapter="sql-lexical",
        )
    ]

    first = list(iter_domain_file_chunks(sql_path))
    second = list(iter_domain_file_chunks(sql_path))
    assert first == second
    assert len(first) >= 2
    assert [chunk.index for chunk in first] == list(range(len(first)))
    assert {chunk.domain for chunk in first} == {DomainKind.SQL}
    assert {chunk.adapter for chunk in first} == {"sql-lexical"}
    assert all(
        len(chunk.text.encode("utf-8")) <= DOMAIN_INPUT_SIZE_LIMIT_BYTES
        for chunk in first
    )
    assert all(chunk.text.endswith(";") for chunk in first[:-1])
    assert b"".join(chunk.text.encode("utf-8") for chunk in first) == encoded
    assert "".join(chunk.text for chunk in first) == sql

    byte_cursor = 0
    char_cursor = 0
    source_identity_ids: set[int] = set()
    for chunk in first:
        assert (chunk.byte_start, chunk.char_start) == (byte_cursor, char_cursor)
        assert encoded[chunk.byte_start : chunk.byte_end].decode("utf-8") == chunk.text
        assert chunk.byte_end - chunk.byte_start == len(chunk.text.encode("utf-8"))
        assert chunk.char_end - chunk.char_start == len(chunk.text)
        assert chunk.source_size_bytes == len(encoded)

        provenance = {"source_span": chunk.source_span(), "repo": "Kitware/VTK"}
        parsed = parse_domain_document(
            sql_path,
            chunk.text,
            source_doc_id=19,
            provenance=provenance,
        )
        parsed.validate()
        assert parsed.domain == DomainKind.SQL
        assert set(parsed.domain_ids) == {int(DomainKind.SQL)}
        assert set(parsed.confidence_ids) == {int(ParseConfidence.HEURISTIC)}
        assert parsed.metadata["provenance"] == provenance
        assert parsed.source_identity_registry
        source_identity_ids.add(parsed.source_identity_ids[0])

        first_token = parsed.tokens[0]
        last_token = parsed.tokens[-1]
        parsed.add_edge(0, len(parsed.tokens) - 1, DomainEdgeKind.AST_PARENT)
        token_ids = list(range(1, len(parsed.tokens) + 1))
        wrapped = wrap_with_domain_tokens(parsed.to_packet(token_ids))
        start_id, end_id = delimiter_token_ids(DomainKind.SQL)
        wrapped_ids = np.asarray(wrapped.token_ids).tolist()
        assert wrapped_ids == [start_id, *token_ids, end_id]
        assert wrapped.graph_edges.to_triples() == [
            (1, len(parsed.tokens), int(DomainEdgeKind.AST_PARENT))
        ]
        assert sql[chunk.char_start + first_token.start :].startswith(first_token.text)
        assert sql[chunk.char_start + last_token.start :].startswith(last_token.text)

        byte_cursor = chunk.byte_end
        char_cursor = chunk.char_end

    assert (byte_cursor, char_cursor) == (len(encoded), len(sql))
    assert len(source_identity_ids) == 1

    monkeypatch.setattr(Path, "read_text", original_read_text)

    metadata_doc = index_project.build_build_doc(
        str(sql_path),
        "SELECT 1;",
        "sql",
        source_root=str(tmp_path),
        project_id="Kitware/VTK",
        source_span=first[0].source_span(),
    )
    assert metadata_doc["source_span"] == first[0].source_span()
    assert metadata_doc["domain_parse_info"]["source_span"] == first[0].source_span()

    def lightweight_build_doc(
        filepath: str,
        text: str,
        build_kind: str,
        **kwargs,
    ) -> dict[str, object]:
        assert filepath == str(sql_path)
        assert build_kind == "sql"
        assert len(text.encode("utf-8")) <= DOMAIN_INPUT_SIZE_LIMIT_BYTES
        return {
            "text": text,
            "domain_kind": int(DomainKind.SQL),
            "source_span": kwargs["source_span"],
        }

    monkeypatch.setattr(index_project, "build_build_doc", lightweight_build_doc)
    monkeypatch.setattr(index_project, "load_compile_commands", lambda *_args: None)
    monkeypatch.setattr(
        index_project,
        "detect_build_context",
        lambda *_args, **_kwargs: ({}, [], None),
    )
    monkeypatch.setattr(index_project, "get_default_compile_args", lambda *_args: [])
    monkeypatch.setattr(index_project, "check_memory_limit", lambda *_args, **_kwargs: None)
    docs: list[dict[str, object]] = []
    returned = index_project.process_project(
        str(tmp_path),
        enriched=True,
        emit_doc=docs.append,
        project_id="Kitware/VTK",
    )
    assert returned == []
    assert "".join(str(doc["text"]) for doc in docs) == sql
    assert [doc["source_span"] for doc in docs] == [
        chunk.source_span() for chunk in first
    ]


def test_large_configure_chunks_without_aborting_repo_and_preserves_identity(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    from cppmega_mlx.data import domain_ingestion
    from tools.clang_indexer import index_project

    configure = _aseprite_style_large_configure()
    encoded = configure.encode("utf-8")
    configure_path = tmp_path / "third_party/cityhash/configure"
    configure_path.parent.mkdir(parents=True)
    configure_path.write_bytes(encoded)

    assert index_project.find_build_files(str(tmp_path)) == [
        (str(configure_path), "configure")
    ]
    assert discover_project_domain_files(tmp_path, include_cpp=False) == [
        DiscoveredDomainFile(
            path=configure_path,
            domain=DomainKind.CONFIGURE,
            adapter="configure-shell",
        )
    ]

    first = list(iter_domain_file_chunks(configure_path))
    second = list(iter_domain_file_chunks(configure_path))
    assert first == second
    assert len(first) >= 2
    assert [chunk.index for chunk in first] == list(range(len(first)))
    assert {chunk.domain for chunk in first} == {DomainKind.CONFIGURE}
    assert {chunk.adapter for chunk in first} == {"configure-shell"}
    assert all(
        len(chunk.text.encode("utf-8")) <= DOMAIN_INPUT_SIZE_LIMIT_BYTES
        for chunk in first
    )
    assert all(
        chunk.source_span()["chunk_limit_bytes"] == DOMAIN_INPUT_SIZE_LIMIT_BYTES
        for chunk in first
    )
    assert all(chunk.text.endswith("\n") for chunk in first[:-1])
    assert all(chunk.split_reason == "line_boundary" for chunk in first[:-1])
    assert b"".join(chunk.text.encode("utf-8") for chunk in first) == encoded

    byte_cursor = 0
    char_cursor = 0
    for chunk in first:
        assert (chunk.byte_start, chunk.char_start) == (byte_cursor, char_cursor)
        assert encoded[chunk.byte_start : chunk.byte_end].decode("utf-8") == chunk.text
        byte_cursor = chunk.byte_end
        char_cursor = chunk.char_end
    assert (byte_cursor, char_cursor) == (len(encoded), len(configure))

    small_chunks = list(iter_domain_file_chunks(configure_path, max_chunk_bytes=4096))
    sample_docs = [
        index_project.build_build_doc(
            str(configure_path),
            chunk.text,
            "configure",
            source_root=str(tmp_path),
            project_id="aseprite/aseprite",
            source_span=chunk.source_span(),
        )
        for chunk in small_chunks[:2]
    ]
    assert {doc["domain_kind"] for doc in sample_docs} == {int(DomainKind.CONFIGURE)}
    assert {doc["build_kind"] for doc in sample_docs} == {"configure"}
    assert len({doc["source_identity_id"] for doc in sample_docs}) == 1
    assert all(doc["shell_edges"] for doc in sample_docs)
    for chunk, doc in zip(small_chunks[:2], sample_docs, strict=True):
        assert doc["source_span"] == chunk.source_span()
        assert doc["domain_parse_info"]["source_span"] == chunk.source_span()
        for key in (
            "domain_ids",
            "domain_role_ids",
            "domain_entity_ids",
            "domain_scope_ids",
            "domain_source_doc_ids",
            "domain_source_identity_ids",
            "domain_confidence_ids",
        ):
            assert len(doc[key]) == len(chunk.text), key

    parsed = parse_domain_document(configure_path, small_chunks[0].text)
    parsed.add_edge(0, len(parsed.tokens) - 1, DomainEdgeKind.SHELL_COMMAND_FILE)
    token_ids = list(range(1, len(parsed.tokens) + 1))
    wrapped = wrap_with_domain_tokens(parsed.to_packet(token_ids))
    start_id, end_id = delimiter_token_ids(DomainKind.CONFIGURE)
    assert np.asarray(wrapped.token_ids).tolist() == [start_id, *token_ids, end_id]
    assert (
        1,
        len(parsed.tokens),
        int(DomainEdgeKind.SHELL_COMMAND_FILE),
    ) in wrapped.graph_edges.to_triples()

    emitted: list[dict[str, object]] = []

    def lightweight_build_doc(
        filepath: str,
        text: str,
        build_kind: str,
        **kwargs,
    ) -> dict[str, object]:
        assert filepath == str(configure_path)
        assert build_kind == "configure"
        assert len(text.encode("utf-8")) <= DOMAIN_INPUT_SIZE_LIMIT_BYTES
        return {
            "text": text,
            "domain_kind": int(DomainKind.CONFIGURE),
            "source_span": kwargs["source_span"],
        }

    monkeypatch.setattr(index_project, "build_build_doc", lightweight_build_doc)
    monkeypatch.setattr(index_project, "load_compile_commands", lambda *_args: None)
    monkeypatch.setattr(
        index_project,
        "detect_build_context",
        lambda *_args, **_kwargs: ({}, [], None),
    )
    monkeypatch.setattr(index_project, "get_default_compile_args", lambda *_args: [])
    monkeypatch.setattr(index_project, "check_memory_limit", lambda *_args, **_kwargs: None)
    returned = index_project.process_project(
        str(tmp_path),
        enriched=True,
        emit_doc=emitted.append,
        project_id="aseprite/aseprite",
    )
    assert returned == []
    assert "".join(str(doc["text"]) for doc in emitted) == configure
    assert [doc["source_span"] for doc in emitted] == [
        chunk.source_span() for chunk in first
    ]

    assert domain_ingestion.resolve_domain_parser(configure_path).domain == (
        DomainKind.CONFIGURE
    )


def test_binary_asset_is_excluded_before_domain_read(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    from cppmega_mlx.data.domain_ingestion import resolve_domain_parser
    from tools.clang_indexer import index_project

    png_path = tmp_path / "site/en/community/images/Linkedin-Logo.png"
    png_path.parent.mkdir(parents=True)
    png_path.write_bytes(
        b"\x89PNG\r\n\x1a\n\0ld: warning: unresolved external symbol\n"
    )

    original_open = Path.open

    def reject_binary_asset_read(path: Path, *args, **kwargs):
        if path == png_path:
            raise AssertionError("binary assets must be filtered before domain reads")
        return original_open(path, *args, **kwargs)

    monkeypatch.setattr(Path, "open", reject_binary_asset_read)
    assert resolve_domain_parser(png_path, "ld: warning: unresolved external symbol").name == (
        "raw-output"
    )
    assert index_project.find_build_files(str(tmp_path)) == []
    assert index_project.find_shell_files(str(tmp_path)) == []
    assert discover_project_domain_files(tmp_path, include_cpp=False) == []


def test_later_bash_chunks_keep_shebang_domain_and_source_identity(
    tmp_path: Path,
) -> None:
    from tools.clang_indexer import index_project

    script_path = tmp_path / "scripts/release.sh"
    script_path.parent.mkdir(parents=True)
    script_path.write_text(
        "#!/usr/bin/env bash\n" + "printf '%s\\n' release > /dev/null\n" * 32
    )
    chunks = list(iter_domain_file_chunks(script_path, max_chunk_bytes=128))
    assert len(chunks) > 2
    assert {chunk.domain for chunk in chunks} == {DomainKind.BASH}
    assert {chunk.adapter for chunk in chunks} == {"bash"}

    docs = [
        index_project.build_build_doc(
            str(script_path),
            chunk.text,
            "bash",
            source_root=str(tmp_path),
            project_id="owner/repo",
            source_span=chunk.source_span(),
        )
        for chunk in (chunks[0], chunks[-1])
    ]
    assert {doc["domain_kind"] for doc in docs} == {int(DomainKind.BASH)}
    assert len({doc["source_identity_id"] for doc in docs}) == 1
    assert all(doc["shell_edges"] for doc in docs)


@pytest.mark.parametrize(
    ("relative_path", "line", "domain", "adapter"),
    [
        (
            "CMakeLists.txt",
            "add_library(generated STATIC generated.cpp)\n",
            DomainKind.CMAKE,
            "cmake",
        ),
        (
            "Makefile",
            "generated: dependency\n\t@printf '%s\\n' generated\n",
            DomainKind.MAKE,
            "make",
        ),
    ],
)
def test_line_oriented_build_domains_use_lossless_bounded_chunks(
    tmp_path: Path,
    relative_path: str,
    line: str,
    domain: DomainKind,
    adapter: str,
) -> None:
    path = tmp_path / relative_path
    text = line * 16
    path.write_text(text)

    chunks = list(iter_domain_file_chunks(path, max_chunk_bytes=128))
    assert len(chunks) > 1
    assert {chunk.domain for chunk in chunks} == {domain}
    assert {chunk.adapter for chunk in chunks} == {adapter}
    assert all(len(chunk.text.encode("utf-8")) <= 128 for chunk in chunks)
    assert all(chunk.split_reason == "line_boundary" for chunk in chunks[:-1])
    assert "".join(chunk.text for chunk in chunks) == text


def test_utf16le_large_sql_chunks_preserve_original_encoded_byte_spans(
    tmp_path: Path,
) -> None:
    sql = (
        "-- generated SQL\r\n"
        + "INSERT INTO audit_log VALUES (N'café', N'Москва');\r\n" * 32
    )
    encoded = b"\xff\xfe" + sql.encode("utf-16-le")
    path = tmp_path / "legacy/schema.sql"
    path.parent.mkdir(parents=True)
    path.write_bytes(encoded)

    assert discover_project_domain_files(tmp_path) == [
        DiscoveredDomainFile(
            path=path,
            domain=DomainKind.SQL,
            adapter="sql-lexical",
        )
    ]
    chunks = list(iter_domain_file_chunks(path, max_chunk_bytes=128))
    assert len(chunks) > 2
    assert "".join(chunk.text for chunk in chunks) == sql
    assert {chunk.source_encoding for chunk in chunks} == {"utf-16-le"}
    assert all(chunk.byte_end - chunk.byte_start <= 128 for chunk in chunks)

    byte_cursor = 0
    char_cursor = 0
    for chunk in chunks:
        assert (chunk.byte_start, chunk.char_start) == (byte_cursor, char_cursor)
        raw = encoded[chunk.byte_start : chunk.byte_end]
        if chunk.index == 0:
            assert raw.startswith(b"\xff\xfe")
            raw = raw[2:]
        assert raw.decode("utf-16-le") == chunk.text
        assert chunk.source_span()["source_encoding"] == "utf-16-le"
        byte_cursor = chunk.byte_end
        char_cursor = chunk.char_end
    assert (byte_cursor, char_cursor) == (len(encoded), len(sql))


def test_utf16be_chunks_do_not_split_non_bmp_code_points(tmp_path: Path) -> None:
    sql = "SELECT N'😀';\n" * 12
    encoded = b"\xfe\xff" + sql.encode("utf-16-be")
    path = tmp_path / "legacy-be.sql"
    path.write_bytes(encoded)

    chunks = list(iter_domain_file_chunks(path, max_chunk_bytes=24))
    assert "".join(chunk.text for chunk in chunks) == sql
    assert {chunk.source_encoding for chunk in chunks} == {"utf-16-be"}
    for chunk in chunks:
        raw = encoded[chunk.byte_start : chunk.byte_end]
        if chunk.index == 0:
            raw = raw[2:]
        assert raw.decode("utf-16-be") == chunk.text


@pytest.mark.parametrize(
    ("codec", "bom"),
    [
        ("utf-32-le", b"\xff\xfe\0\0"),
        ("utf-32-be", b"\0\0\xfe\xff"),
    ],
)
def test_utf32_cmake_chunks_preserve_original_encoded_byte_spans(
    tmp_path: Path,
    codec: str,
    bom: bytes,
) -> None:
    text = "set(VALUE \"😀\")\n" * 12
    encoded = bom + text.encode(codec)
    path = tmp_path / "BOM-UTF-32.cmake"
    path.write_bytes(encoded)

    assert discover_project_domain_files(tmp_path) == [
        DiscoveredDomainFile(
            path=path,
            domain=DomainKind.CMAKE,
            adapter="cmake",
        )
    ]
    chunks = list(iter_domain_file_chunks(path, max_chunk_bytes=40))
    assert "".join(chunk.text for chunk in chunks) == text
    assert {chunk.source_encoding for chunk in chunks} == {codec}
    for chunk in chunks:
        raw = encoded[chunk.byte_start : chunk.byte_end]
        if chunk.index == 0:
            raw = raw[len(bom) :]
        assert raw.decode(codec) == chunk.text


def test_windows_1252_sql_is_decoded_strictly_without_replacement(
    tmp_path: Path,
) -> None:
    sql = "-- Microsoft’s legacy export\r\nSELECT 'café';\r\n"
    encoded = sql.encode("cp1252")
    path = tmp_path / "legacy.sql"
    path.write_bytes(encoded)

    chunks = list(iter_domain_file_chunks(path, max_chunk_bytes=32))
    assert "".join(chunk.text for chunk in chunks) == sql
    assert {chunk.source_encoding for chunk in chunks} == {"windows-1252"}
    assert b"".join(chunk.text.encode("cp1252") for chunk in chunks) == encoded
    assert all(chunk.byte_end - chunk.byte_start <= 32 for chunk in chunks)


def test_single_trailing_nul_is_preserved_as_explicit_source_terminator(
    tmp_path: Path,
) -> None:
    sql = "BEGIN TRANSACTION;\r\nCOMMIT TRANSACTION;\r\n"
    encoded = sql.encode("utf-8") + b"\0"
    path = tmp_path / "terminated.sql"
    path.write_bytes(encoded)

    chunks = list(iter_domain_file_chunks(path, max_chunk_bytes=24))
    assert "".join(chunk.text for chunk in chunks) == sql
    assert chunks[-1].byte_end == len(encoded)
    assert all(chunk.source_trailing_nul_bytes == 1 for chunk in chunks)
    assert all(
        chunk.source_span()["source_trailing_nul_bytes"] == 1
        for chunk in chunks
    )
    rebuilt = b"".join(chunk.text.encode("utf-8") for chunk in chunks) + b"\0"
    assert rebuilt == encoded


def test_large_domain_policy_skips_untyped_and_rejects_malformed_text(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    oversized = b"x" * (DOMAIN_INPUT_SIZE_LIMIT_BYTES + 1)

    unsupported_root = tmp_path / "unsupported"
    unsupported_root.mkdir()
    (unsupported_root / "payload.opaque").write_bytes(oversized)
    assert discover_project_domain_files(unsupported_root) == []

    build_root = tmp_path / "build"
    build_root.mkdir()
    cmake_path = build_root / "CMakeLists.txt"
    cmake_path.write_bytes(oversized)
    assert discover_project_domain_files(build_root) == [
        DiscoveredDomainFile(
            path=cmake_path,
            domain=DomainKind.CMAKE,
            adapter="cmake",
        )
    ]
    assert "".join(chunk.text for chunk in iter_domain_file_chunks(cmake_path)) == (
        oversized.decode("utf-8")
    )
    with pytest.raises(ValueError, match="max_chunk_bytes must be between"):
        list(
            iter_domain_file_chunks(
                build_root / "CMakeLists.txt",
                max_chunk_bytes=DOMAIN_INPUT_SIZE_LIMIT_BYTES + 1,
            )
        )

    binary_root = tmp_path / "binary"
    binary_root.mkdir()
    (binary_root / "schema.sql").write_bytes(b"SELECT 1;\0" + oversized)
    with pytest.raises(ValueError, match="binary domain input contains NUL byte"):
        discover_project_domain_files(binary_root)

    invalid_root = tmp_path / "invalid"
    invalid_root.mkdir()
    (invalid_root / "schema.sql").write_bytes(b"SELECT 1;" + oversized + b"\x81")
    with pytest.raises(ValueError, match="invalid UTF-8 or Windows-1252"):
        discover_project_domain_files(invalid_root)

    unreadable_root = tmp_path / "unreadable"
    unreadable_root.mkdir()
    unreadable = unreadable_root / "schema.sql"
    unreadable.write_bytes(b"SELECT 1;" + oversized)
    original_open = Path.open

    def fail_open(path: Path, *args, **kwargs):
        if path == unreadable:
            raise OSError("simulated large SQL read failure")
        return original_open(path, *args, **kwargs)

    monkeypatch.setattr(Path, "open", fail_open)
    with pytest.raises(OSError, match="failed to read domain input.*simulated"):
        discover_project_domain_files(unreadable_root)


def test_domain_discovery_skips_binary_generic_text_candidates(
    tmp_path: Path,
) -> None:
    generic = tmp_path / "compiler-output.txt"
    generic.write_bytes(b"error: invalid candidate\0binary payload")

    assert discover_project_domain_files(tmp_path) == []


def test_domain_discovery_accepts_windows_1252_generic_text_candidates(
    tmp_path: Path,
) -> None:
    generic = tmp_path / "compiler-output.txt"
    generic.write_bytes(
        "main.cpp:12:3: error: compiler’s invalid candidate\n".encode("cp1252")
    )

    assert discover_project_domain_files(tmp_path) == [
        DiscoveredDomainFile(
            path=generic,
            domain=DomainKind.COMPILER_DIAGNOSTIC,
            adapter="clang-diagnostic",
        )
    ]


@pytest.mark.parametrize("name", ["module.py", "script.ksh"])
def test_domain_discovery_rejects_non_utf8_explicit_domain_files(
    tmp_path: Path,
    name: str,
) -> None:
    explicit = tmp_path / name
    explicit.write_bytes(b"explicit domain\x81")

    with pytest.raises(ValueError, match="invalid UTF-8 or Windows-1252"):
        discover_project_domain_files(tmp_path)


@pytest.mark.parametrize("name", ["module.py", "script.ksh", "Makefile"])
def test_domain_discovery_can_audit_and_skip_invalid_explicit_inputs(
    tmp_path: Path,
    name: str,
) -> None:
    explicit = tmp_path / name
    explicit.write_bytes(b"explicit domain\x81")
    rejected: list[tuple[Path, str]] = []

    discovered = discover_project_domain_files(
        tmp_path,
        invalid_input_handler=lambda path, exc: rejected.append((path, str(exc))),
    )

    assert discovered == []
    assert len(rejected) == 1
    assert rejected[0][0] == explicit
    assert rejected[0][1].startswith("invalid UTF-8 or Windows-1252")
