from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

from cppmega_mlx.data.domain_ingestion import (
    DOMAIN_INPUT_SIZE_LIMIT_BYTES,
    DiscoveredDomainFile,
    discover_project_domain_files,
    iter_domain_file_chunks,
    parse_domain_document,
)
from cppmega_mlx.data.domain_packet import wrap_with_domain_tokens
from cppmega_mlx.data.domain_schema import (
    DomainEdgeKind,
    DomainKind,
    ParseConfidence,
    delimiter_token_ids,
)


def _vtk_style_large_sql() -> str:
    statement = (
        'INSERT INTO "alias_name" VALUES('
        "'geodetic_datum','EPSG','6143',"
        "'Côte d''Ivoire; alias','EPSG'); "
    )
    repetitions = DOMAIN_INPUT_SIZE_LIMIT_BYTES // len(statement.encode("utf-8")) + 32
    text = "-- generated by scripts/build_db.py\n" + statement * repetitions + "\n"
    assert len(text.encode("utf-8")) > DOMAIN_INPUT_SIZE_LIMIT_BYTES
    return text


def test_large_sql_chunks_are_bounded_deterministic_and_lossless(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    from tools.clang_indexer import index_project

    sql = _vtk_style_large_sql()
    encoded = sql.encode("utf-8")
    sql_path = tmp_path / "ThirdParty/libproj/vtklibproj/data/sql/alias_name.sql"
    sql_path.parent.mkdir(parents=True)
    sql_path.write_bytes(encoded)

    original_read_text = Path.read_text

    def reject_whole_file_read(path: Path, *args, **kwargs):
        if path == sql_path:
            raise AssertionError("large SQL discovery must not call Path.read_text")
        return original_read_text(path, *args, **kwargs)

    monkeypatch.setattr(Path, "read_text", reject_whole_file_read)
    assert discover_project_domain_files(tmp_path) == [
        DiscoveredDomainFile(
            path=sql_path,
            domain=DomainKind.SQL,
            adapter="sql-lexical",
        )
    ]

    first = list(iter_domain_file_chunks(sql_path))
    second = list(iter_domain_file_chunks(sql_path))
    assert first == second
    assert len(first) >= 2
    assert [chunk.index for chunk in first] == list(range(len(first)))
    assert {chunk.domain for chunk in first} == {DomainKind.SQL}
    assert {chunk.adapter for chunk in first} == {"sql-lexical"}
    assert all(
        len(chunk.text.encode("utf-8")) <= DOMAIN_INPUT_SIZE_LIMIT_BYTES
        for chunk in first
    )
    assert all(chunk.text.endswith(";") for chunk in first[:-1])
    assert b"".join(chunk.text.encode("utf-8") for chunk in first) == encoded
    assert "".join(chunk.text for chunk in first) == sql

    byte_cursor = 0
    char_cursor = 0
    source_identity_ids: set[int] = set()
    for chunk in first:
        assert (chunk.byte_start, chunk.char_start) == (byte_cursor, char_cursor)
        assert encoded[chunk.byte_start : chunk.byte_end].decode("utf-8") == chunk.text
        assert chunk.byte_end - chunk.byte_start == len(chunk.text.encode("utf-8"))
        assert chunk.char_end - chunk.char_start == len(chunk.text)
        assert chunk.source_size_bytes == len(encoded)

        provenance = {"source_span": chunk.source_span(), "repo": "Kitware/VTK"}
        parsed = parse_domain_document(
            sql_path,
            chunk.text,
            source_doc_id=19,
            provenance=provenance,
        )
        parsed.validate()
        assert parsed.domain == DomainKind.SQL
        assert set(parsed.domain_ids) == {int(DomainKind.SQL)}
        assert set(parsed.confidence_ids) == {int(ParseConfidence.HEURISTIC)}
        assert parsed.metadata["provenance"] == provenance
        assert parsed.source_identity_registry
        source_identity_ids.add(parsed.source_identity_ids[0])

        first_token = parsed.tokens[0]
        last_token = parsed.tokens[-1]
        parsed.add_edge(0, len(parsed.tokens) - 1, DomainEdgeKind.AST_PARENT)
        token_ids = list(range(1, len(parsed.tokens) + 1))
        wrapped = wrap_with_domain_tokens(parsed.to_packet(token_ids))
        start_id, end_id = delimiter_token_ids(DomainKind.SQL)
        wrapped_ids = np.asarray(wrapped.token_ids).tolist()
        assert wrapped_ids == [start_id, *token_ids, end_id]
        assert wrapped.graph_edges.to_triples() == [
            (1, len(parsed.tokens), int(DomainEdgeKind.AST_PARENT))
        ]
        assert sql[chunk.char_start + first_token.start :].startswith(first_token.text)
        assert sql[chunk.char_start + last_token.start :].startswith(last_token.text)

        byte_cursor = chunk.byte_end
        char_cursor = chunk.char_end

    assert (byte_cursor, char_cursor) == (len(encoded), len(sql))
    assert len(source_identity_ids) == 1

    monkeypatch.setattr(Path, "read_text", original_read_text)

    metadata_doc = index_project.build_build_doc(
        str(sql_path),
        "SELECT 1;",
        "sql",
        source_root=str(tmp_path),
        project_id="Kitware/VTK",
        source_span=first[0].source_span(),
    )
    assert metadata_doc["source_span"] == first[0].source_span()
    assert metadata_doc["domain_parse_info"]["source_span"] == first[0].source_span()

    def lightweight_build_doc(
        filepath: str,
        text: str,
        build_kind: str,
        **kwargs,
    ) -> dict[str, object]:
        assert filepath == str(sql_path)
        assert build_kind == "sql"
        assert len(text.encode("utf-8")) <= DOMAIN_INPUT_SIZE_LIMIT_BYTES
        return {
            "text": text,
            "domain_kind": int(DomainKind.SQL),
            "source_span": kwargs["source_span"],
        }

    monkeypatch.setattr(index_project, "build_build_doc", lightweight_build_doc)
    monkeypatch.setattr(index_project, "load_compile_commands", lambda *_args: None)
    monkeypatch.setattr(
        index_project,
        "detect_build_context",
        lambda *_args: ({}, [], None),
    )
    monkeypatch.setattr(index_project, "get_default_compile_args", lambda *_args: [])
    monkeypatch.setattr(index_project, "check_memory_limit", lambda *_args, **_kwargs: None)
    docs: list[dict[str, object]] = []
    returned = index_project.process_project(
        str(tmp_path),
        enriched=True,
        emit_doc=docs.append,
        project_id="Kitware/VTK",
    )
    assert returned == []
    assert "".join(str(doc["text"]) for doc in docs) == sql
    assert [doc["source_span"] for doc in docs] == [
        chunk.source_span() for chunk in first
    ]


def test_large_domain_policy_rejects_or_explicitly_skips_non_text_inputs(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    oversized = b"x" * (DOMAIN_INPUT_SIZE_LIMIT_BYTES + 1)

    unsupported_root = tmp_path / "unsupported"
    unsupported_root.mkdir()
    (unsupported_root / "payload.opaque").write_bytes(oversized)
    assert discover_project_domain_files(unsupported_root) == []

    build_root = tmp_path / "build"
    build_root.mkdir()
    (build_root / "CMakeLists.txt").write_bytes(oversized)
    with pytest.raises(ValueError, match="CMAKE has no large-input chunk policy"):
        discover_project_domain_files(build_root)
    with pytest.raises(ValueError, match="max_chunk_bytes must be between"):
        list(
            iter_domain_file_chunks(
                build_root / "CMakeLists.txt",
                max_chunk_bytes=DOMAIN_INPUT_SIZE_LIMIT_BYTES + 1,
            )
        )

    binary_root = tmp_path / "binary"
    binary_root.mkdir()
    (binary_root / "schema.sql").write_bytes(b"SELECT 1;\0" + oversized)
    with pytest.raises(ValueError, match="binary domain input contains NUL byte"):
        discover_project_domain_files(binary_root)

    invalid_root = tmp_path / "invalid"
    invalid_root.mkdir()
    (invalid_root / "schema.sql").write_bytes(b"SELECT 1;" + oversized + b"\xff")
    with pytest.warns(RuntimeWarning, match="skipping non-UTF-8 domain input"):
        assert discover_project_domain_files(invalid_root) == []

    unreadable_root = tmp_path / "unreadable"
    unreadable_root.mkdir()
    unreadable = unreadable_root / "schema.sql"
    unreadable.write_bytes(b"SELECT 1;" + oversized)
    original_open = Path.open

    def fail_open(path: Path, *args, **kwargs):
        if path == unreadable:
            raise OSError("simulated large SQL read failure")
        return original_open(path, *args, **kwargs)

    monkeypatch.setattr(Path, "open", fail_open)
    with pytest.raises(OSError, match="failed to read domain input.*simulated"):
        discover_project_domain_files(unreadable_root)
