"""Configuration dataclasses for cppmega_mlx."""

from cppmega_mlx.config.model import (
    DEFAULT_ATTENTION_HEADS,
    DEFAULT_DSA_A_LAYER_RANKS,
    DEFAULT_FFN_HIDDEN_SIZE,
    DEFAULT_HIDDEN_SIZE,
    DEFAULT_NAM56R_DEPTH,
    DEFAULT_NAM56R_PATTERN,
    DEFAULT_SEQ_LEN,
    LOCAL_PROFILE_VOCAB_SIZE,
    MEGACPP_TOKENIZER_VOCAB_SIZE,
    DSAConfig,
    M2RNNConfig,
    Mamba3Config,
    MLAConfig,
    MoeConfig,
    Nam56RModelConfig,
    NgramHashConfig,
    SourceStructureEnvConfig,
    StructureConfig,
    VocabMetadata,
)

__all__ = [
    "DEFAULT_ATTENTION_HEADS",
    "DEFAULT_DSA_A_LAYER_RANKS",
    "DEFAULT_FFN_HIDDEN_SIZE",
    "DEFAULT_HIDDEN_SIZE",
    "DEFAULT_NAM56R_DEPTH",
    "DEFAULT_NAM56R_PATTERN",
    "DEFAULT_SEQ_LEN",
    "DSAConfig",
    "LOCAL_PROFILE_VOCAB_SIZE",
    "M2RNNConfig",
    "MEGACPP_TOKENIZER_VOCAB_SIZE",
    "MLAConfig",
    "Mamba3Config",
    "MoeConfig",
    "Nam56RModelConfig",
    "NgramHashConfig",
    "SourceStructureEnvConfig",
    "StructureConfig",
    "VocabMetadata",
]
