"""MLX-native inference helpers."""

from cppmega_mlx.inference.engine import (
    ContiguousKVCache,
    ContiguousKVCacheConfig,
    PromptCacheEntry,
    clone_contiguous_kv_cache,
    kv_cache_position,
    make_contiguous_kv_cache,
    prefill_contiguous_kv_cache,
    rollback_contiguous_kv_cache,
    trim_contiguous_kv_cache,
)
from cppmega_mlx.inference.constraints import (
    JsonConstrainedLogitsProcessor,
    JsonTokenIds,
    LogitsProcessor,
)
from cppmega_mlx.inference.infilling import build_fim_prompt_ids
from cppmega_mlx.inference.generation import (
    GenerationChunk,
    build_prompt_cache,
    generate_tokens,
    generate_tokens_mtp_self_speculative,
    generate_tokens_speculative,
    generate_tokens_with_prompt_cache,
    generate_tokens_with_kv_cache,
    next_token_logits,
    stream_generate_tokens,
)
from cppmega_mlx.inference.quantization import (
    InferenceQuantizationConfig,
    make_quantized_kv_cache,
    quantize_kv_cache,
    quantize_linear_for_inference,
    should_start_kv_quantization,
    validate_kv_head_dim,
)
from cppmega_mlx.inference.sampling import sample_next_token
from cppmega_mlx.inference.serve import create_local_generation_app
from cppmega_mlx.inference.serving import (
    ContinuousBatchScheduler,
    PAGED_ATTENTION_NOT_INTEGRATED_MESSAGE,
    PagedKVBlockManager,
    PagedKVBlockManagerConfig,
    SchedulerOutput,
    SequenceRequest,
    build_paged_block_table,
    gather_paged_kv,
    require_model_integrated_paged_attention,
    scatter_paged_kv,
)
from cppmega_mlx.inference.side_channels import (
    AdapterUnavailableError,
    AdapterCapabilities,
    ClangCodeMetadataAdapter,
    CodeMetadataAdapter,
    GoCodeMetadataAdapter,
    InferenceFailPolicy,
    InferenceSideChannelBuilder,
    InferenceSideChannelCacheComponents,
    InferenceSideChannelResult,
    PythonCodeMetadataAdapter,
    RustCodeMetadataAdapter,
    TokenMetadata,
    UnavailableCodeMetadataAdapter,
    builtin_code_metadata_adapters,
    get_builtin_code_metadata_adapter,
    normalize_code_language,
)
from cppmega_mlx.inference.speculative_decode import (
    speculative_acceptance,
    speculative_acceptance_batch,
    typical_acceptance,
    typical_acceptance_batch,
)
from cppmega_mlx.inference.tool_use import (
    ToolUseBlock,
    ToolUseSpecialTokenIds,
    compute_tool_use_loss_mask,
    encode_tool_use_template,
    render_tool_use_template,
)

__all__ = [
    "ContiguousKVCache",
    "ContiguousKVCacheConfig",
    "ContinuousBatchScheduler",
    "GenerationChunk",
    "AdapterUnavailableError",
    "AdapterCapabilities",
    "ClangCodeMetadataAdapter",
    "CodeMetadataAdapter",
    "InferenceFailPolicy",
    "InferenceQuantizationConfig",
    "InferenceSideChannelBuilder",
    "InferenceSideChannelCacheComponents",
    "InferenceSideChannelResult",
    "JsonConstrainedLogitsProcessor",
    "JsonTokenIds",
    "LogitsProcessor",
    "GoCodeMetadataAdapter",
    "PAGED_ATTENTION_NOT_INTEGRATED_MESSAGE",
    "PagedKVBlockManager",
    "PagedKVBlockManagerConfig",
    "PythonCodeMetadataAdapter",
    "PromptCacheEntry",
    "RustCodeMetadataAdapter",
    "SchedulerOutput",
    "SequenceRequest",
    "TokenMetadata",
    "ToolUseBlock",
    "ToolUseSpecialTokenIds",
    "UnavailableCodeMetadataAdapter",
    "build_prompt_cache",
    "build_fim_prompt_ids",
    "build_paged_block_table",
    "builtin_code_metadata_adapters",
    "gather_paged_kv",
    "scatter_paged_kv",
    "clone_contiguous_kv_cache",
    "compute_tool_use_loss_mask",
    "create_local_generation_app",
    "encode_tool_use_template",
    "generate_tokens",
    "generate_tokens_mtp_self_speculative",
    "generate_tokens_speculative",
    "generate_tokens_with_prompt_cache",
    "generate_tokens_with_kv_cache",
    "get_builtin_code_metadata_adapter",
    "kv_cache_position",
    "make_contiguous_kv_cache",
    "make_quantized_kv_cache",
    "next_token_logits",
    "normalize_code_language",
    "prefill_contiguous_kv_cache",
    "quantize_kv_cache",
    "quantize_linear_for_inference",
    "require_model_integrated_paged_attention",
    "render_tool_use_template",
    "rollback_contiguous_kv_cache",
    "sample_next_token",
    "should_start_kv_quantization",
    "speculative_acceptance",
    "speculative_acceptance_batch",
    "stream_generate_tokens",
    "trim_contiguous_kv_cache",
    "typical_acceptance",
    "typical_acceptance_batch",
    "validate_kv_head_dim",
]
