"""Training, loss, and checkpoint helpers."""

from cppmega_mlx.training.compiled import (
    CompiledPretrainingStep,
    PretrainingMetrics,
    PretrainingState,
    STABLE_BATCH_KEYS,
    normalize_compiled_batch,
)
from cppmega_mlx.training.checkpoint import (
    FORMAT_NAME,
    FORMAT_VERSION,
    GRAD_ACCUM_NAME,
    METADATA_NAME,
    OPTIMIZER_NAME,
    RNG_MODE_NOT_SAVED,
    RNG_MODE_SEED,
    SHARDING_MODE_SINGLE_FILE,
    SHARD_INDEX_NAME,
    WEIGHTS_NAME,
    load_checkpoint,
    save_checkpoint,
)
from cppmega_mlx.training.eval import EvalMetrics, evaluate_batches
from cppmega_mlx.training.loop import TrainStepResult, make_adamw, one_step_train
from cppmega_mlx.training.loss import next_token_cross_entropy
from cppmega_mlx.training.mlx_lm_adapter import (
    MLX_LM_DENSE_BATCH_KEYS,
    MLXLMAPIInfo,
    MLXLMBatchRouteMetadata,
    MLXLMTrainerIntegrationUnsupported,
    REQUIRED_TRAINER_PARAMETERS,
    STRUCTURE_FIELD_NAMES,
    TRAINER_ADAPTER_SAVE_FIELDS,
    TRAINER_API_NAMES,
    TRAINER_MODULE,
    TRAINING_ARGS_MEMORY_POLICY_FIELDS,
    UNSUPPORTED_TRAINER_INTEGRATION_REASON,
    as_mlx_lm_loss_args,
    as_mlx_lm_token_mapping,
    describe_mlx_lm_batch_route_metadata,
    describe_mlx_lm_trainer_apis,
    require_supported_mlx_lm_trainer_integration,
)
from cppmega_mlx.training.profile import (
    HotspotEvidence,
    KernelAdoptionAssessment,
    KernelAdoptionBlocked,
    MemorySnapshot,
    ProfileContext,
    ProfileMetrics,
    StepProfiler,
    assess_kernel_adoption,
    hotspot_from_profile_metrics,
    profile_context,
    profile_step,
    require_kernel_hotspot_evidence,
    reset_peak_memory,
    summarize_hotspots,
    synchronize,
)

__all__ = [
    "CompiledPretrainingStep",
    "EvalMetrics",
    "FORMAT_NAME",
    "FORMAT_VERSION",
    "GRAD_ACCUM_NAME",
    "HotspotEvidence",
    "KernelAdoptionAssessment",
    "KernelAdoptionBlocked",
    "METADATA_NAME",
    "MLX_LM_DENSE_BATCH_KEYS",
    "MLXLMAPIInfo",
    "MLXLMBatchRouteMetadata",
    "MLXLMTrainerIntegrationUnsupported",
    "MemorySnapshot",
    "OPTIMIZER_NAME",
    "PretrainingMetrics",
    "PretrainingState",
    "ProfileContext",
    "ProfileMetrics",
    "REQUIRED_TRAINER_PARAMETERS",
    "RNG_MODE_NOT_SAVED",
    "RNG_MODE_SEED",
    "SHARDING_MODE_SINGLE_FILE",
    "SHARD_INDEX_NAME",
    "STRUCTURE_FIELD_NAMES",
    "TRAINER_ADAPTER_SAVE_FIELDS",
    "TRAINER_API_NAMES",
    "TRAINER_MODULE",
    "TRAINING_ARGS_MEMORY_POLICY_FIELDS",
    "as_mlx_lm_loss_args",
    "as_mlx_lm_token_mapping",
    "assess_kernel_adoption",
    "describe_mlx_lm_batch_route_metadata",
    "describe_mlx_lm_trainer_apis",
    "evaluate_batches",
    "hotspot_from_profile_metrics",
    "load_checkpoint",
    "make_adamw",
    "next_token_cross_entropy",
    "normalize_compiled_batch",
    "one_step_train",
    "profile_context",
    "profile_step",
    "require_kernel_hotspot_evidence",
    "reset_peak_memory",
    "require_supported_mlx_lm_trainer_integration",
    "save_checkpoint",
    "STABLE_BATCH_KEYS",
    "StepProfiler",
    "summarize_hotspots",
    "synchronize",
    "TrainStepResult",
    "UNSUPPORTED_TRAINER_INTEGRATION_REASON",
    "WEIGHTS_NAME",
]
